[[main]]
  name = "Yazılar"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projeler"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Hakkımda"
  pageRef = "about"
  weight = 30

[[main]]
  name = "Kullandıklarım"
  pageRef = "uses"
  weight = 40

[[main]]
  name = "Şu An"
  pageRef = "now"
  weight = 50

[[footer]]
  name = "Etiketler"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 20
